# Generated by Django 5.0.6 on 2024-09-13 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('special_status', 'Can read all books')]},
        ),
    ]
