services:
  web:
    build: .
    ports:
      - '8000:8000'
    command: python django_project/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data: